receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:
    verbosity: normal

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    tls:
      insecure: true

processors:
  filter/ottl:
    error_mode: ignore
    traces:
        span:
            - 'name == "emb-setup"'
  resource:
    attributes:
      - key: service.name
        value: OTLP Exporter
        action: insert
  batch:

service:
  telemetry:
    logs:
      level: debug

  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, zipkin]
      processors: [resource, batch]
